name: suds-v2
services:
  - name: web
    source_dir: /
    dockerfile_path: Dockerfile
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: NEXTAUTH_URL
        scope: RUN_TIME
        value: ${APP_URL}
      - key: NEXTAUTH_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: GOOGLE_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
      - key: GOOGLE_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: GITHUB_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
      - key: GITHUB_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: DISCORD_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
      - key: DISCORD_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ADMIN_EMAILS
        scope: RUN_TIME
        type: SECRET
databases:
  - name: suds-db
    engine: PG
    production: false
    version: "16"
